# This is a basic workflow to help you get started with Actions

name: Edit script

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: 
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs commands using the runners shell
    - name: Edit file
      run: |
        cd browser_monitor_scripts
        (echo "//monitorId=6766,7868" && cat 'script_monitor_id_1573.js') > filename1 && mv filename1 'script_monitor_id_1573.js'
        cd ../
    - name: Commit files # transfer the new html files back into the repository
      run: |
        git config --local user.name "SC-sync-bot"
        git add ./browser_monitor_scripts
        git commit -m "Updating scripts"
    - name: Push changes # push the output folder to your repo
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true
