name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  
    name: Test changed-files
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v1.1.3

      - name: List all modified files
        env:
          SC_API_BASE_URL: ${{ secrets.SC_API_BASE_URL }}
          SC_API_KEY: ${{ secrets.SC_API_KEY }}
        run: |
          for file in "${{ steps.changed-files.outputs.all_modified_files }}"; do
            echo "$file was modified"
            export SCRIPT_FILES="$file"
            echo $SCRIPT_FILES
          done

          filesArray=($SCRIPT_FILES)

          for file in $filesArray; do
            echo "sending api request========="
            echo "------------------------------"
            if [[ $file == *"browser_monitor_scripts"* ]]; then
              script_content=$( base64 $file )

              echo 'data==========='
              body='{"script":"'$script_content'"}'
              body='{"script":"Ly8gVGhpcyBzY3JpcHQgbG9hZHMgdGhlIHdlYnBhZ2UgYW5kIHRha2VzIGEgc2NyZWVuc2hvdCBvZiB0aGUgbG9hZGVkIHBhZ2UuCmFzeW5jIGZ1bmN0aW9uIHRlc3RQYWdlKHBhZ2UpIHsKICAvLyBSZXBsYWNlIFlPVVJfV0VCUEFHRV9VUkwgd2l0aCBVUkwgb2YgdGhlIHdlYnBhZ2UgdG8gYmUgbW9uaXRvcmVkCiAgYXdhaXQgcGFnZS5nb3RvKCJodHRwczovL3NzdXZhbGlqYS5naXRodWIuaW8vaW5kZXguaHRtbCMiKTsKICBhd2FpdCBwYWdlLmdvdG8oImh0dHBzOi8vc3N1dmFsaWphLmdpdGh1Yi5pby9pbmRleC5odG1sIyIpOwogIGF3YWl0IHBhZ2UuZ290bygiaHR0cHM6Ly9zc3V2YWxpamEuZ2l0aHViLmlvL2luZGV4Lmh0bWwjIik7CiAgYXdhaXQgcGFnZS5nb3RvKCJodHRwczovL3NzdXZhbGlqYS5naXRodWIuaW8vaW5kZXguaHRtbCMiKTsKICBhd2FpdCBwYWdlLnNjcmVlbnNob3QoeyBwYXRoOiAnc2NyZWVuc2hvdC5qcGcnIH0pOwp9Cm1vZHVsZS5leHBvcnRzID0gdGVzdFBhZ2U7"}'

              api_url=https://apps.test.sematext.com/synthetics-api/api/v3/apps/3981/monitors/browser/1153

              curl -v --location --request PUT ${api_url} \
                --header 'authorization: apiKey '${SC_API_KEY} \
                  --header 'Content-Type: application/json' \
                    --data-raw ${body} 
            fi

          done


      
