name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # windows-latest | macos-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v1.1.3

      - name: List all modified files
        run: |
          for file in "${{ steps.changed-files.outputs.all_modified_files }}"; do
            echo "$file was modified"
            export SCRIPT_FILES="$file"
            echo $SCRIPT_FILES  
          done

          filesArray=($SCRIPT_FILES)

          for file in $filesArray; do
            echo "sending api request========="
            echo "------------------------------"
            if [[ $file == *"browser_monitor_scripts"* ]]; then
              script_content=$( base64 $file )

              api_url=${{ secrets.SC_API_BASE_URL }}
              api_url+='/apps/3981/monitors/browser/1153'

              auth_header='Authorization: apiKey '
              auth_header+=${{ secrets.SC_API_KEY}}

              curl --location --request PUT $api_url \
              --header $auth_header \
              --header 'Content-Type: application/json' \
              --data '{"script":"'$script_content'"}'
            fi

          done


      
