name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  
    name: Test changed-files
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v1.1.3

      - name: List all modified files
        env:
          SC_API_BASE_URL: ${{ secrets.SC_API_BASE_URL }}
          SC_API_KEY: ${{ secrets.SC_API_KEY }}
        run: |
          for file in "${{ steps.changed-files.outputs.modified_files }}"; do
            echo "$file was modified"
            export SCRIPT_FILES="$file"
            echo $SCRIPT_FILES
          done

          filesArray=($SCRIPT_FILES)

          for file in $filesArray; do
            echo "sending api request========="
            echo "------------------------------"
            if [[ $file == *"browser_monitor_scripts"* ]]; then
              script_content=$( base64 -w 0 $file )

              body='{"script":"'$script_content'"}'

              line=$( head -n 1 $file )
              IFS='=' read -r -a monitor_ids <<< "$line"
              IFS='=' read -r -a monitos <<< "$monitor_ids"

              for monitor_id in $monitors; do
                api_url=${SC_API_BASE_URL}'/synthetics-api/api/v3/apps/3981/monitors/browser/'${monitor_id}
                curl -v --location --request PUT ${api_url} \
                  --header 'authorization: apiKey '${SC_API_KEY} \
                    --header 'Content-Type: application/json' \
                      --data-raw ${body}

              done 
            fi

          done


      
